stages:
  - Static Analysis
  - Test
  - Release
pylint:
  stage: Static Analysis
  image: python:3.12-slim
  before_script:
    - python -V
    - python -m pip install -r requirements.txt
    - python -m pip install pylint
  script:
    - pylint --fail-under=7 src | tee pylint_report.txt
  artifacts:
    when: always
    paths:
      - pylint_report.txt

integration-tests:
  stage: Test
  image: docker:27.1.1
  services:
    - docker:27.1.1-dind
  before_script:
    - docker info
  script:
    - docker compose -f ci/compose.test.yaml up --exit-code-from create-group-pytest

release-image:
  stage: Release
  image: docker:27.1.1
  services:
    - docker:27.1.1-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:latest" -t "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH" --all-tags