apiVersion: v1
kind: Secret
metadata:
  name: env-vars-production
type: Opaque
stringData:
  stage: "production-k8s"
  db_conn: "mysql+mysqlconnector://cs302:cs302@host.minikube.internal:3306"
  # rabbitmq_username: "guest"
  # rabbitmq_password: "guest"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
  rabbitmq_host: "host.minikube.internal"
  rabbitmq_port: "5672"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  # users_service_url: "http://localhost/api/v1/users"
  # groups_service_url: "http://localhost/api/v1/groups"
  # events_service_url: "http://localhost/api/v1/events"
  # payment_service_url: "http://localhost/api/v1/payment"
  # create_group_service_url: "http://localhost/api/v1/create-group"
  # join_group_service_url: "http://localhost/api/v1/join-group"
  # make_a_payment_service_url: "http://localhost/api/v1/make-a-payment"
  graphql_service_url_internal: "http://graphql-service:80"
  users_service_url_internal: "http://users-service:30000"
  groups_service_url_internal: "http://groups-service:30001"
  events_service_url_internal: "http://events-service:30002"
  payment_service_url_internal: "http://payment-service:30003"
  create_group_service_url_internal: "http://create-group-service:30004"
  join_group_service_url_internal: "http://join-group-service:30005"
  make_a_payment_service_url_internal: "http://make-a-payment-service:30006"
  notifications_service_url_internal: "http://notifications-service:30007"

  # Stripe API keys for testing
  STRIPE_SECRET_KEY: "sk_test_51QIZd9RraH8diVTWW7ufEoXH47b9KzTpdN1hQq8PxV7wzJHYaFkWTxiWkvdjlJHd8TGnrpcmrrL23uHkKPXfYba100PHNJT9hj"
  STRIPE_PUBLISHABLE_KEY: "pk_test_51QIZd9RraH8diVTWuyEvUPa61UZLcMYiVYDeXyw4Sev567BmAghs2LYZANYBuPs6NNPbZfDPN6nIYEo3gcEc3dLH00nGhrkiVj"
  STRIPE_WEBHOOK_SECRET: "whsec_34fe1fb383f13e0150bfd7e1b84e77a939722cf30d06fa032d5ff30f931511a1"

  # Email  configuration
  SENDER_EMAIL: "animeetcs302@gmail.com"
  SENDER_PASSWORD: "trxh ftfm icqk tvne"
  SMTP_SERVER: "smtp.gmail.com"
  SMTP_PORT: "587"

  # Base portion of URL that Stripe sends user to after payment completion
  APP_DOMAIN: "http://localhost"

  
