FROM python:3.12-slim
WORKDIR /usr/src/app
COPY requirements.txt ./
COPY ci/requirements.test.txt ./
COPY src/* ./src/
COPY tests/*.py ./tests/
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements.test.txt
CMD python -m pytest