services:
  ####################################
  # RabbitMQ for Messaging
  ####################################
  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ####################################
  # Pytest on Notifications Service
  ####################################
  notifications-pytest:
    build:
      context: ../
      dockerfile: ci/Dockerfile.test
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SENDER_EMAIL: animeet.app@gmail.com
      SENDER_PASSWORD: animeet123
    command: python -m pytest