FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy production and test dependencies
COPY requirements.txt ./
COPY ci/requirements.test.txt ./
COPY ci/wait-for-it.sh .

# Copy the source code and test files to the container
COPY src/* ./src/
COPY tests/*.py ./tests/

# Make wait-for-it.sh executable
RUN chmod +x wait-for-it.sh

# Install dependencies for both production and testing
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements.test.txt

# Command to wait for RabbitMQ and then run pytest
CMD ./wait-for-it.sh rabbitmq:5672 -- python -m pytest