version: "3.8"

services:
  graphql-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}  # Load Stripe key from .env
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SQLALCHEMY_DATABASE_URI=mysql+mysqlconnector://root:root@db:3306/payment  # Database URI
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment
    ports:
      - "3306:3306"  # Expose MySQL port

  # Optional: Add a migration service if needed
  migrate:
    image: graphql-app
    command: flask db upgrade
    depends_on:
      - db
      - graphql-app
